import {
    Aden,
    Brannan,
    Brooklyn,
    Clarendon,
    Earlybird,
    Gingham,
    Hudson,
    Inkwell,
    Kelvin,
    Lark,
    Lofi,
    Maven,
    Mayfair,
    Moon,
    Nashville,
    Perpetua,
    Reyes,
    Rise,
    Slumber,
    Stinson,
    Toaster,
    Valencia,
    Walden,
    Willow,
    Xpro2,
    Normal,
} from 'react-native-image-filter-kit'


export type Filter = typeof Aden

export const filters: [string, Filter][] = [
    ['Normal', Normal],
    ['Aden', Aden],
    ['Brannan', Brannan],
    ['Brooklyn', Brooklyn],
    ['Clarendon', Clarendon],
    // ['Earlybird', Earlybird],
    // ['Gingham', Gingham],
    // ['Hudson', Hudson],
    // ['Inkwell', Inkwell],
    // ['Kelvin', Kelvin],
    // ['Lark', Lark],
    // ['Lofi', Lofi],
    // ['Maven', Maven],
    // ['Mayfair', Mayfair],
    // ['Moon', Moon],
    // ['Nashville', Nashville],
    // ['Perpetua', Perpetua],
    // ['Reyes', Reyes],
    // ['Rise', Rise],
    // ['Slumber', Slumber],
    // ['Stinson', Stinson],
    // ['Toaster', Toaster],
    ['Valencia', Valencia],
    ['Walden', Walden],
    ['Willow', Willow],
    ['Xpro2', Xpro2],
]